### ISSUE TITLE
make testable translation file compatible with crowdin.com

### ISSUE THREAD

**Issue by janbarasek** [mathematicator-core/engine#12]

**Comment by comradekingu** [comment]
Crowdin is a lackluster tool with spying and tracking. Avoid it and use Weblate instead. :)

**Comment by miloshavlicek** [comment]
@comradekingu I like both, Crowdin (it's userfriendly) and also Weblate. However, with Weblate it's a little bit more complicated. It has a free "cloud" offering for opensource, however, nobody reacts to applications. With Crowdin it's faster to start and end-users know it more.
P.S. Spying and tracking is everywhere ;-)

**Comment by janbarasek** [comment]
@comradekingu I don't think tracking is a problem for open source, where all content is available openly and for free.

**Comment by comradekingu** [comment]
@janbarasek That isn't the tracking I am talking about. Crowdin does none of that kind of openness, and instead uses your activity to sell it to advertisers and data collection agencies behind the scenes.
Having to restrict a project to having no sources of income to comply with the "gratis" inclusion policies of Crowdin is a problem, and it doesn't help the libre software ecosystem to use a closed source that demands one contribute to its closed translation memory in doing so. Read the terms and conditions and the cookie policy.
Not being able to enjoy the benefits of the software, by contributing to it, is misaligned.

**Comment by miloshavlicek** [comment]
Solved in #16

**Comment by janbarasek** [comment]
Thanks!
