### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by miloshavlicek** [mathematicator-core/engine#3]
Each class in `src/` directory should have its unit test in `test/` directory.

It would help to understand how the package works and it would also prevent unexpected errors.

**Comment by janbarasek** [comment]
Yes, I will implement it.

Can you send PR with code coverage test to check that all tests exist?

**Comment by janbarasek** [comment]
I implemented all tests with 100% coverage. Easy!

![Snímek obrazovky 2020-05-03 v 21 58 14](https://user-images.githubusercontent.com/4738758/80924773-36591600-8d8b-11ea-9864-4d0ec28692e2.png)
