### ISSUE TITLE
Unwanted dependencies

### ISSUE THREAD

**Issue by miloshavlicek** [mathematicator-core/engine#6]
In this package we depends on `"latte/latte"`, however it's used only once for escaping HTML text. I think we can escape HTML with `htmlspecialchars` PHP function (the same as is Filters::escapeHtmlText method implementation).

Dependency on `tracy/tracy` is also not necessary. Tracy is used only in two files and it is possible to implement it as an optional dependency. It can be in "suggest": {} section of package.json and if somebody wants to use it, he can request it in project dependencies. In code we can call Tracy Debugger this way:

```
if (class_exists('\Tracy\Debugger')) {
    Debugger::log(...);
}
```

I also think that Router and Presenters (`"nette/application"`) shouldn't be responsibility of this package. I think that it can be responsibility of [baraja-core/vikitron](https://github.com/baraja-core/vikitron) application.

It causes unnecessary dependencies of other packages that use this package.

It would be also helpful to describe responsibility of this package compared to other packages (e.g. `mathematicator-core/calculator`) and describe some basic usages.

What is your opinion?

**Comment by janbarasek** [comment]
@miloshavlicek Thanks for it.

Latte was removed and escaping function replaced to `htmlspecialchars`.

Tracy is optional now.

Nette Application was removed and link logic is hardcoded now (in future it can be changed). What do you think about? https://github.com/mathematicator-core/engine/blob/master/src/Entity/Context.php#L165

I think it is done and we can close issue.

**Comment by miloshavlicek** [comment]
Wow, I didn't expect such a quick response. Thanks for it!
